DROP TABLE IF EXISTS OCCURENCE;
DROP TABLE IF EXISTS PIP_SPREAD;
DROP TABLE IF EXISTS CURRENCY_MOVEMENTS_VS_USD;

CREATE TABLE OCCURENCE (
	ID integer not null,
	CROSS_NAME varchar(16),
	TRADE_SESSION_ROLL_COUNT integer not null, -- how many periods it's rallied against dollar
	FREQUENCY integer not null,
	DOLLAR_UP integer not null,
	HAPPENED timestamp,
	UP_PROB_NEXT double, 					-- based on this occurence count prop followed by up
	DOWN_PROB_NEXT double,					-- based on this occurence count prop followed by down 
	ACTIVE integer not null,
	PREV_ACTIVE integer not null,
	TRADE_SESSION integer not null, 		-- DAY PERIOD or OVER NIGHT PERIOD
	CROSS_PRICE float,
	PRIMARY KEY (ID)
);

CREATE TABLE PIP_SPREAD (
	ID INT NOT NULL AUTO_INCREMENT,
	TRADE_SESSION integer not null,
	CROSS_NAME varchar(16),	
	DOLLAR_UP integer not null,
	DIFF float,	
	PRIMARY KEY (ID)
);

-- PART OF RULES ENGINE
CREATE TABLE CURRENCY_MOVEMENTS_VS_USD (
	ID INT NOT NULL AUTO_INCREMENT,
	SESSION_USD_UP_COUNT INT NOT NULL,
	FOLLOWED_UP_OCCURED INT NOT NULL,
	FOLLOWED_DOWN_OCCURED INT NOT NULL,
	SELL_USD INT NOT NULL,	
	BUY_USD INT NOT NULL,
	PRIMARY KEY (ID)
);



-- ALTER TABLE OCCURENCE CHANGE PERIOD_ROLL_COUNT TRADE_SESSION_ROLL_COUNT integer not null;
--  ALTER TABLE PIP_SPREAD CHANGE PERIOD TRADE_SESSION integer not null;

DELETE FROM NAME_MAPPING WHERE ID = 5;
DELETE FROM NAME_MAPPING WHERE ID = 6;
DELETE FROM NAME_MAPPING WHERE ID = 7;

INSERT INTO NAME_MAPPING (ID, TABLE_NAME, REST_NAME) VALUES(5, 'OCCURENCE', 'occurence');
INSERT INTO NAME_MAPPING (ID, TABLE_NAME, REST_NAME) VALUES(6, 'PIP_SPREAD', 'pipSpread');
INSERT INTO NAME_MAPPING (ID, TABLE_NAME, REST_NAME) VALUES(7, 'CURRENCY_MOVEMENTS_VS_USD', 'currencyMovementsVsUsd');


