DROP VIEW IF EXISTS CURRENCY_LIST_VIEW;
DROP VIEW IF EXISTS AVERAGES_VIEW;
DROP VIEW IF EXISTS STANDARD_DEV_VIEW;
DROP VIEW IF EXISTS VIEW_OF_AVERAGES_VIEW;
DROP VIEW IF EXISTS CURRENCY_LIST_VIEW_ACTIVE_RECORD;
DROP VIEW IF EXISTS CURRENCY_OCCURENCE_STATUS_VIEW;
DROP VIEW IF EXISTS PERIOD_MOVES_STATUS_VIEW;
DROP VIEW IF EXISTS TRADE_SESSION_CHANGE_AUD;
DROP VIEW IF EXISTS TRADE_SESSION_CHANGE_CAD;
DROP VIEW IF EXISTS TRADE_SESSION_CHANGE_GBP;
DROP VIEW IF EXISTS TRADE_SESSION_CHANGE_EUR;
DROP VIEW IF EXISTS TRADE_SESSION_CHANGE_JPY;
DROP VIEW IF EXISTS TRADE_SESSION_CHANGE_CHF;
DROP VIEW IF EXISTS AVERAGES_VIEW_ID;
DROP VIEW IF EXISTS TOTAL_OVER_TIME_VIEW;
DROP VIEW IF EXISTS SESSION_REF_MAX;

CREATE VIEW CURRENCY_OCCURENCE_STATUS_VIEW
   AS
SELECT ID, CROSS_NAME AS CUR,TRADE_SESSION_ROLL_COUNT AS CNT,FREQUENCY AS FREQ,DOLLAR_UP AS UPDWN,UP_PROB_NEXT AS UPN,DOWN_PROB_NEXT AS DNX,TRADE_SESSION AS PER,CROSS_PRICE AS PRI FROM OCCURENCE WHERE CROSS_NAME = 'EUR' AND TRADE_SESSION =  (SELECT MAX(TRADE_SESSION) FROM OCCURENCE)
UNION ALL
SELECT ID, CROSS_NAME,TRADE_SESSION_ROLL_COUNT,FREQUENCY,DOLLAR_UP,UP_PROB_NEXT,DOWN_PROB_NEXT,TRADE_SESSION,CROSS_PRICE FROM OCCURENCE WHERE CROSS_NAME = 'CAD' AND TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM OCCURENCE)
UNION ALL
SELECT ID, CROSS_NAME,TRADE_SESSION_ROLL_COUNT,FREQUENCY,DOLLAR_UP,UP_PROB_NEXT,DOWN_PROB_NEXT,TRADE_SESSION,CROSS_PRICE FROM OCCURENCE WHERE CROSS_NAME = 'CHF' AND TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM OCCURENCE)
UNION ALL
SELECT ID, CROSS_NAME,TRADE_SESSION_ROLL_COUNT,FREQUENCY,DOLLAR_UP,UP_PROB_NEXT,DOWN_PROB_NEXT,TRADE_SESSION,CROSS_PRICE FROM OCCURENCE WHERE CROSS_NAME = 'GBP' AND TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM OCCURENCE)
UNION ALL
SELECT ID, CROSS_NAME,TRADE_SESSION_ROLL_COUNT,FREQUENCY,DOLLAR_UP,UP_PROB_NEXT,DOWN_PROB_NEXT,TRADE_SESSION,CROSS_PRICE FROM OCCURENCE WHERE CROSS_NAME = 'JPY' AND TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM OCCURENCE)
UNION ALL
SELECT ID,CROSS_NAME,TRADE_SESSION_ROLL_COUNT,FREQUENCY,DOLLAR_UP,UP_PROB_NEXT,DOWN_PROB_NEXT,TRADE_SESSION,CROSS_PRICE FROM OCCURENCE WHERE CROSS_NAME = 'AUD' AND TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM OCCURENCE);

CREATE VIEW PERIOD_MOVES_STATUS_VIEW
   AS
SELECT DISTINCT ID, TRADE_SESSION, SUM(DOLLAR_UP) AS MOVES_UP, COUNT(*) - SUM(DOLLAR_UP) AS MOVES_DOWN FROM OCCURENCE GROUP BY TRADE_SESSION;

CREATE VIEW CURRENCY_LIST_VIEW
   	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD ORDER BY CROSS_NAME,TRADE_SESSION ASC;

CREATE VIEW TRADE_SESSION_CHANGE_AUD
	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD WHERE CROSS_NAME = 'AUD' ORDER BY TRADE_SESSION ASC;

CREATE VIEW TRADE_SESSION_CHANGE_CAD
	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD WHERE CROSS_NAME = 'CAD' ORDER BY TRADE_SESSION ASC;

CREATE VIEW TRADE_SESSION_CHANGE_GBP
	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD WHERE CROSS_NAME = 'GBP' ORDER BY TRADE_SESSION ASC;

CREATE VIEW TRADE_SESSION_CHANGE_EUR 
	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD WHERE CROSS_NAME = 'EUR' ORDER BY TRADE_SESSION ASC;

CREATE VIEW TRADE_SESSION_CHANGE_JPY 
	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD WHERE CROSS_NAME = 'JPY' ORDER BY TRADE_SESSION ASC;

CREATE VIEW TRADE_SESSION_CHANGE_CHF 
	AS
SELECT ID, TRADE_SESSION, CROSS_NAME, DOLLAR_UP, DIFF from PIP_SPREAD WHERE CROSS_NAME = 'CHF' ORDER BY TRADE_SESSION ASC;

CREATE VIEW AVERAGES_VIEW
   AS
SELECT ID, CROSS_NAME, AVG(DOLLAR_UP)*100 AS AVERAGE_UP, AVG(DIFF) AS DIFFERENC from PIP_SPREAD GROUP BY CROSS_NAME;

CREATE VIEW STANDARD_DEV_VIEW
   AS
SELECT ID, CROSS_NAME, AVG(DOLLAR_UP)*100 AS AVERAGE_UP, AVG(DIFF) AS AVERAGE, STD(DIFF)+AVG(DIFF) AS STD_ABOVE, AVG(DIFF)-STD(DIFF) AS STD_BELOW, STD(DIFF) AS STDEV from PIP_SPREAD GROUP BY CROSS_NAME;

CREATE VIEW VIEW_OF_AVERAGES_VIEW
   AS
SELECT avg(MOVES_UP) as UPMVS, avg(MOVES_DOWN) as DOWNMVS FROM PERIOD_MOVES_STATUS_VIEW;

CREATE VIEW CURRENCY_LIST_VIEW_ACTIVE_RECORD
   AS
SELECT * FROM CURRENCY_LIST_VIEW WHERE TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM CURRENCY_LIST_VIEW);

CREATE VIEW AVERAGES_VIEW_ID
 AS
SELECT ID, CROSS_NAME FROM AVERAGES_VIEW;

CREATE VIEW TOTAL_OVER_TIME_VIEW
 AS 
SELECT min(ID) as ID, sum(DIFF) as SESSION_SUM from PIP_SPREAD GROUP BY TRADE_SESSION ORDER BY ID ASC;

CREATE VIEW SESSION_REF_MAX
 AS 
SELECT 0 AS ID, max(TRADE_SESSION)+1 AS MAX_SESSION from CURRENCY_PRICE;




