TRUNCATE OCCURENCE;
TRUNCATE PIP_SPREAD;

SELECT INVOKE_POPULATION_PROC(0, (select max(TRADE_SESSION)+1 from CURRENCY_PRICE)) AS aNumber; 

CALL CALCULATE_TRADE_SESSION_DIFFS('EUR');
CALL CALCULATE_TRADE_SESSION_DIFFS('CAD');
CALL CALCULATE_TRADE_SESSION_DIFFS('CHF');
CALL CALCULATE_TRADE_SESSION_DIFFS('GBP');
CALL CALCULATE_TRADE_SESSION_DIFFS('JPY');
CALL CALCULATE_TRADE_SESSION_DIFFS('AUD');

SELECT * FROM OCCURENCE WHERE CROSS_NAME = 'EUR';
SELECT * FROM OCCURENCE WHERE CROSS_NAME = 'CAD';
SELECT * FROM OCCURENCE WHERE CROSS_NAME = 'CHF';
SELECT * FROM OCCURENCE WHERE CROSS_NAME = 'GBP';
SELECT * FROM OCCURENCE WHERE CROSS_NAME = 'JPY';
SELECT * FROM OCCURENCE WHERE CROSS_NAME = 'AUD';

SELECT "---------------------------------------------";
SELECT * FROM PERIOD_MOVES_STATUS_VIEW;
SELECT * FROM VIEW_OF_AVERAGES_VIEW;

SELECT "---------------------------------------------";
SELECT * FROM CURRENCY_OCCURENCE_STATUS_VIEW;

-- CURRENCY LIST VIEW
SELECT "---------------------------";
SELECT * FROM CURRENCY_LIST_VIEW;

SELECT * FROM CURRENCY_LIST_VIEW WHERE TRADE_SESSION = (SELECT MAX(TRADE_SESSION) FROM CURRENCY_LIST_VIEW);

--  AVERAGES VIEW
SELECT "--------------------------";
SELECT * FROM AVERAGES_VIEW;

-- STANDARD DEVIATION VIEW
SELECT "--------------------------";
SELECT * FROM STANDARD_DEV_VIEW;